[package]
name = "lenavire-contribution-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
async-trait = "0.1.87"
chrono = { version = "0.4.40", features = ["serde"] }
diesel = { version = "2.2.8", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15.0"
env_logger = "0.11.7"
log = "0.4.26"
mockall = "0.11"
r2d2 = "0.8.10"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
